loginID: 'uid-login-form-0-wb-id-identifier-field'
passwordID: 'uid-labeled-text-field-1-wb-id-field'
assignment_btn: '_qm98q6h'
next_btn: '//*[@id="assignments-container"]/div[2]/button[2]'
end_btn: '_1161iwl'
exit_btn: '_xrgghrk'
retry: 2